TRASFONDOS = [
    'Acolyte',
    'Anthropologist',
    'Archaeologist',
    'Astral Drifter',
    'Athlete',
    'Baldur s Gate Acolyte',
    'Baldur s Gate Charlatan',
    'Baldur s Gate Criminal',
    'Baldur s Gate Entertainer',
    'Baldur s Gate Folk Hero',
    'Baldur s Gate Guild Artisan',
    'Baldur s Gate Hermit',
    'Baldur s Gate Noble',
    'Baldur s Gate Outlander',
    'Baldur s Gate Sage',
    'Baldur s Gate Sailor',
    'Baldur s Gate Soldier',
    'Baldur s Gate Urchin',
    'Charlatan',
    'City Watch',
    'City Watch (Investigator)',
    'Clan Crafter',
    'Cloistered Scholar',
    'Courtier',
    'Criminal',
    'Criminal (Spy)',
    'Entertainer',
    'Entertainer (Gladiator)',
    'Faceless',
    'Faction Agent',
    'Far Traveler',
    'Feylost',
    'Fisher',
    'Folk Hero',
    'Gate Warden',
    'Giant Foundling',
    'Guild Artisan',
    'Guild Artisan (Guild Merchant)',
    'Haunted',
    'Hermit',
    'House Agent',
    'Inheritor',
    'Investigator',
    'Knight of the Order',
    'Marine',
    'Mercenary Veteran',
    'Noble',
    'Noble (Knight)',
    'Noble (Retainers)',
    'Outlander',
    'Planar Philosopher',
    'Rune Carver',
    'Sage',
    'Sailor',
    'Sailor (Pirate)',
    'Shipwright',
    'Smuggler',
    'Soldier',
    'Urban Bounty Hunter',
    'Urchin',
    'Uthgardt Tribe Member',
    'Waterdhavian Noble',
    'Wildspacer',
    'Witchlight Hand',
]
