CLASES = {
    'Artifice': [
        'Alquimista',
        'Blindado',
        'Artillero',
        'Herrero de Combate'
    ],
    'Bárbaro': [
        'Guardian Ancestral',
        'Battlerager (Camorrista)',
        'Bestia (Beast)',
        'Berserker',
        'Gigante',
        'Juggernaut',
        'Heraldo de la Tormenta',
        'Guerrero Totemico',
        'Corazon Salvaje',
        'Magia Salvaje',
        'Arbol del Mundo (Yggdrasil)',
        'Fanatico (Zealot)'
    ],
    'Bardo': [
        'Creacion',
        'Baile (Dance)',
        'Elocuencia',
        'Glamur (Glamour)',
        'Conocimiento Transmitido (Lore)',
        'Espiritus',
        'Espada',
        'Tragedia',
        'Valor',
        'Susuros'
    ],
    'Brujo': [
        'Archiadas',
        'Celestial',
        'Profundo',
        'Demoniaco',
        'Genio',
        'Antiguo (Great Old One)',
        'Hexblade (Arma Maldita)',
        'No-Muerto',
        'Eterno'
    ],
    'Clérigo': [
        'Ambicion',
        'Arcano',
        'Sangre',
        'Muerte',
        'Forja',
        'Tumba',
        'Conocimiento',
        'Vida',
        'Luz',
        'Luna',
        'Naturaleza',
        'Orden',
        'Paz',
        'Solidaridad',
        'Fuerza',
        'Tempestad',
        'Engaños',
        'Crepusculo',
        'War',
        'Zeal'
    ],
    'Druida': [
        'Alejado (Blighted)',
        'Sueños',
        'Tierra',
        'Luna',
        'Pastor',
        'Esporas',
        'Estrellas',
        'Fuego Salavaje'
    ],
    'Explorador': [
        'Maestro de Bestia',
        'Guardian Dragon',
        'Vagabundo Feerico',
        'Acechador Sombrio',
        'Caminante del Horizonte',
        'Cazador',
        'Cazador de Monstruos',
        'Guardian del Enjambre'
    ],
    'Guerrero': [
        'Arquero Arcano',
        'Maestro de Batalla',
        'Caballero (Cavalier)',
        'Campeon',
        'Caballero Eco',
        'Caballero Misterioso',
        'Psiquico',
        'Caballero del Dragon Purpura',
        'Caballero Runico',
        'Samurai'
    ],
    'Hechicero': [
        'Mente Aberrante',
        'Relogero (Clockwork)',
        'Alma Divina',
        'Draconiano',
        'Lunar',
        'Controlador del Fuego (Piromancer)',
        'Niño de las Runas (Runechild)',
        'Sombras',
        'Tormenta',
        'Magia Salvaje'
    ],
    'Mago': [
        'Abjuracion',
        'Cantante de la Hoja (BladeSinger)',
        'Magia de Sangre',
        'Chronoturgia',
        'Conjuracion',
        'Adivinacion',
        'Encantamiento',
        'Evocacion',
        'Graviturgia',
        'Ilusion',
        'Necromancia',
        'Escriba',
        'Trasmutacion',
        'Guerra (WAR)'
    ],
    'Monje': [
        'Ascendente Dragon',
        'Forma Astral',
        'Alma Cobalto',
        'Maestro Borracho',
        'Cuatro Elemental',
        'Kensei',
        'Larga Muerte',
        'Misericordia',
        'Mano Abierta',
        'Sombra',
        'Alma de Sol'
    ],
    'Paladín': [
        'Los Antiguos',
        'Conquista',
        'Corona',
        'Devocion',
        'Gloria',
        'Rompejuramentos',
        'Mar Abierto',
        'Redencion',
        'Venganza',
        'Vigilantes'
    ],
    'Pícaro': [
        'Engaños Magicos (Arcane Trickster)',
        'Asesino',
        'Inquisitivo',
        'Mente Maestra',
        'Fantasma',
        'Explorador',
        'Alma Afilada (SoulKnife)',
        'Espadachin ()',
        'Ladron'
    ],
}