RAZAS = [
    'Aarakocra Lineage (choose)',
    'Aasimar',
    'Aasimar Lineage (choose)',
    'Aasimar',
    'Aasimar (Fallen)',
    'Aasimar (Protector)',
    'Aasimar (Scourge)',
    'Astral Elf Lineage (choose)',
    'Autognome Lineage (choose)',
    'Bugbear Lineage (choose)',
    'Bugbear',
    'Centaur',
    'Centaur Lineage (choose)',
    'Changeling',
    'Changeling Lineage (choose)',
    'Deep Gnome Lineage (choose)',
    'Dhampir Lineage (choose)',
    'Dragonborn (Base)',
    'Dragonborn (Chromatic)',
    'Dragonborn (Draconblood)',
    'Dragonborn (Gem) Lineage (choose)',
    'Dragonborn (Metallic) Lineage (choose)',
    'Dragonborn (Ravenite)',
    'Duergar Lineage (choose)',
    'Dwarf (Duergar)',
    'Dwarf (Hill)',
    'Dwarf (Mark of Warding)',
    'Dwarf (Mountain)',
    'Eladrin Lineage (choose)',
    'Elf (Drow)',
    'Elf (Eladrin)',
    'Elf (High)',
    'Elf (Mark of Shadow)',
    'Elf (Pallid)',
    'Elf (Sea)',
    'Elf (Shadar-kai)',
    'Elf (Wood)',
    'Fairy',
    'Firbolg' ,
    'Genasi (Air) Lineage (choose)',
    'Genasi (Earth) Lineage (choose)',
    'Genasi (Fire) Lineage (choose)',
    'Genasi (Water) Lineage (choose)',
    'Giff',
    'Gith',
    'Gith (Githyanki)',
    'Gith (Githzerai)',
    'Githyanki Lineage (choose)',
    'Githzerai Lineage (choose)',
    'Gnome',
    'Gnome (Deep)',
    'Gnome (Deep/Svirfneblin)',
    'Gnome (Forest)',
    'Gnome (Mark of Scribing)',
    'Gnome (Rock)',
    'Goblin',
    'Goliath Lineage (choose)',
    'Goliath',
    'Hadozee Lineage (choose)',
    'Half-Elf',
    'Half-Elf (Variant; Aquatic Elf Descent)',
    'Half-Elf (Variant; Drow Descent)',
    'Half-Elf (Variant; Mark of Detection)',
    'Half-Elf (Variant; Mark of Storm)',
    'Half-Elf (Variant; Moon Elf or Sun Elf Descent)',
    'Half-Elf (Variant; Wood Elf Descent)',
    'Half-Orc',
    'Half-Orc (Variant; Mark of Finding)',
    'Halfling (Ghostwise)',
    'Halfling (Lightfoot)',
    'Halfling (Lotusden)',
    'Halfling (Mark of Healing)',
    'Halfling (Mark of Hospitality)',
    'Halfling (Stout)',
    'Harengon',
    'Hexblood',
    'Hobgoblin',
    'Human (Mark of Handling)',
    'Human (Mark of Making)',
    'Human (Mark of Passage)',
    'Human (Mark of Sentinel)',
    'Human (Variant)',
    'Human (Variant; Mark of Finding)',
    'Kalashtar',
    'Kender Lineage (choose)',
    'Kenku Lineage (choose)',
    'Kenku',
    'Kobold Lineage (choose)',
    'Kobold',
    'Leonin',
    'Lizardfolk Lineage (choose)',
    'Lizardfolk',
    'Loxodon',
    'Minotaur',
    'Minotaur Lineage (choose)',
    'Orc',
    'Owlin Lineage (choose)',
    'Plasmoid Lineage (choose)',
    'Reborn Lineage (choose)',
    'Satyr',
    'Satyr Lineage (choose)',
    'Sea Elf Lineage (choose)',
    'Shadar-Kai Lineage (choose)',
    'Shifter',
    'Shifter (Beasthide)',
    'Shifter (Longtooth)',
    'Shifter (Swiftstride)',
    'Shifter (Wildhunt)',
    'Simic Hybrid',
    'Tabaxi',
    'Thri-kreen Lineage (choose)',
    'Tiefling (Asmodeus)',
    'Tiefling (Baalzebul)',
    'Tiefling (Base)',
    'Tiefling (Dispater)',
    'Tiefling (Fierna)',
    'Tiefling (Glasya)',
    'Tiefling (Levistus)',
    'Tiefling (Mammon)',
    'Tiefling (Mephistopheles)',
    'Tiefling (Variant; Devils Tongue)',
    'Tiefling (Variant; Hellfire)',
    'Tiefling (Variant; Infernal Legacy)',
    'Tiefling (Variant; Winged)',
    'Tiefling (Zariel)',
    'Tortle Lineage (choose)',
    'Triton',
    'Triton Lineage (choose)',
    'Triton',
    'Vedalken',
    'Verdan',
    'Warforged',
    'Yuan-Ti Lineage (choose)',
    'Yuan-ti Pureblood',
]
